# Generated by Django 5.1.6 on 2025-03-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostal'), ('rural', 'Alojamiento Rural')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destination.municipality')),
            ],
        ),
    ]
