# Generated by Django 5.1.6 on 2025-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='category',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='location',
            field=models.CharField(choices=[('Valle de Aburrá', 'Valle de Aburrá'), ('Oriente Antioqueño', 'Oriente Antioqueño'), ('Suroeste Antioqueño', 'Suroeste Antioqueño'), ('Occidente Antioqueño', 'Occidente Antioqueño'), ('Nordeste Antioqueño', 'Nordeste Antioqueño'), ('Norte Antioqueño', 'Norte Antioqueño'), ('Magdalena Medio Antioqueño', 'Magdalena Medio Antioqueño'), ('Bajo Cauca Antioqueño', 'Bajo Cauca Antioqueño'), ('Urabá Antioqueño', 'Urabá Antioqueño')], max_length=50),
        ),
        migrations.AddField(
            model_name='municipality',
            name='categories',
            field=models.ManyToManyField(related_name='municipalities', to='destination.category'),
        ),
    ]
