# Generated by Django 5.1.6 on 2025-03-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='category',
        ),
        migrations.AlterField(
            model_name='municipality',
            name='location',
            field=models.CharField(choices=[('valle_aburra', 'Valle de Aburrá'), ('oriente', 'Oriente Antioqueño'), ('suroeste', 'Suroeste Antioqueño'), ('occidente', 'Occidente Antioqueño'), ('nordeste', 'Nordeste Antioqueño'), ('norte', 'Norte Antioqueño'), ('magdalena_medio', 'Magdalena Medio Antioqueño'), ('bajo_cauca', 'Bajo Cauca Antioqueño'), ('uraba', 'Urabá Antioqueño')], max_length=50),
        ),
        migrations.AddField(
            model_name='municipality',
            name='categories',
            field=models.ManyToManyField(related_name='municipalities', to='destination.category'),
        ),
    ]
