# Generated by Django 5.1.6 on 2025-03-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destination.municipality')),
            ],
        ),
    ]
