# Generated by Django 5.1.6 on 2025-03-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
