# Generated by Django 5.1.6 on 2025-03-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0009_delete_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('munitipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='destination.municipality')),
            ],
        ),
    ]
