# Generated by Django 5.1.6 on 2025-04-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0012_travelerpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerpost',
            name='categories',
            field=models.ManyToManyField(to='destination.category'),
        ),
        migrations.AddField(
            model_name='travelerpost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='traveler_posts/'),
        ),
        migrations.AddField(
            model_name='travelerpost',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='traveler_posts/'),
        ),
        migrations.AddField(
            model_name='travelerpost',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.municipality'),
        ),
    ]
