# Generated by Django 5.1.6 on 2025-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0013_travelerpost_categories_travelerpost_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('movilidad', 'Movilidad'), ('experiencia', 'Experiencia en un municipio'), ('presupuesto', 'Presupuesto de viaje'), ('recomendados', 'Recomendados increíbles'), ('anecdota', 'Anécdota'), ('consejo', 'Consejo para viajeros'), ('otras', 'Otras')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='travelerpost',
            name='categories',
            field=models.ManyToManyField(to='destination.travelercategory'),
        ),
    ]
