# Generated by Django 5.1.6 on 2025-05-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
    ]
