# Generated by Django 5.1.6 on 2025-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0017_alter_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
