# Generated by Django 5.1.6 on 2025-05-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0016_accommodation_image'),
        ('destination', '0019_accommodation_image'),
    ]

    operations = [
    ]
