# Generated by Django 5.1.6 on 2025-05-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
